# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-25 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Release', models.IntegerField()),
                ('MovieNmae', models.CharField(max_length=100)),
                ('Hero', models.CharField(max_length=100)),
                ('Heroine', models.CharField(max_length=100)),
                ('Rating', models.FloatField()),
            ],
        ),
    ]
