# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-25 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='Release',
            field=models.DateField(),
        ),
    ]
