# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-25 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0002_auto_20190625_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='Release',
            field=models.IntegerField(),
        ),
    ]
